// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alqrhlonwiwkarnatupn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFscXJobG9ud2l3a2FybmF0dXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDcyNDYsImV4cCI6MjA1NDY4MzI0Nn0.trqgXw4NYOXxnYIz-ioDP6c0m10XECExygGP4r5I-Sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);